name: MLOps CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2     

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Run Data Processing Task
        run: | 
          python src/data/run_processing.py \
             --input data/raw/house_data.csv \
             --output data/processed/cleaned_house_data.csv


      - name: Feature Engineering Task
        run: | 
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data.csv \
            --output data/processed/featured_house_data.csv  \
            --preprocessor models/trained/preprocessor.pkl

      - name: MLFlow Server Setup
        run: | 
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlops-server ghcr.io/mlflow/mlflow:latest \
          mlflow server --host 0.0.0.0 \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root /tmp/mlrun           

      - name: Model Training Task
        run: | 
          python src/models/train_model.py \
          --config configs/model_config.yaml \
          --data data/processed/featured_house_data.csv \
          --models-dir models --mlflow-tracking-uri http://localhost:5555          

      - name: MLFlow Delete Server
        run: | 
          docker stop  mlops-server 
          docker rm mlops-server
          docker rmi ghcr.io/mlflow/mlflow:latest
